# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('v_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Real'), ('str', 'String'), ('bool', 'Boolean')], max_length=30, verbose_name='Тип')),
                ('default', models.CharField(default=None, max_length=100, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Змінна',
                'verbose_name_plural': 'Змінні',
                'db_table': 'app_add_ones',
            },
        ),
        migrations.CreateModel(
            name='CodeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва класу')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата сторення')),
            ],
            options={
                'verbose_name': 'Шаблон коду',
                'verbose_name_plural': 'Шаблони коду',
                'db_table': 'app_code_template',
            },
        ),
        migrations.CreateModel(
            name='FuncAddOnes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('f_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Real'), ('str', 'String'), ('bool', 'Boolean')], max_length=30, verbose_name='Тип, що повертає')),
                ('params', models.TextField(blank=True, default='', max_length=100, verbose_name='Параметри [a,b,c=2]')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ones_func', related_query_name='add_ones_func', to='core.CodeTemplate', verbose_name='Мова програмування')),
            ],
            options={
                'verbose_name': 'Функція',
                'verbose_name_plural': 'Функції',
                'db_table': 'app_add_ones_func',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, verbose_name='Значення')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('template', models.TextField(default='', max_length=1500, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Функція',
                'verbose_name_plural': 'Функції',
                'db_table': 'app_function',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, verbose_name='Значення')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('template', models.TextField(default='', max_length=1500, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Ключове слово',
                'verbose_name_plural': 'Ключові слова',
                'db_table': 'app_keyword',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Мова програмування',
                'verbose_name_plural': 'Мови програмування',
                'db_table': 'app_language',
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', related_query_name='keywords', to='core.Language', verbose_name='Мова програмування'),
        ),
        migrations.AddField(
            model_name='function',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', related_query_name='functions', to='core.Language', verbose_name='Мова програмування'),
        ),
        migrations.AddField(
            model_name='codetemplate',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_templates', related_query_name='code_templates', to='core.Language', verbose_name='Мова програмування'),
        ),
        migrations.AddField(
            model_name='addones',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ones', related_query_name='add_ones', to='core.CodeTemplate', verbose_name='Мова програмування'),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set([('language', 'value')]),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together=set([('language', 'value')]),
        ),
    ]
