# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 16:14
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codetemplate',
            name='created_file',
            field=models.FileField(default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='E:\\Study\\CourseWork\\CodeGenerator\\CodeGenerator\\static'), upload_to='files'),
        ),
    ]
